version: '3.9'

services:
  mariadb:
    build:
      context: ./mariadb
      dockerfile: Dockerfile_mariadb
    container_name: mariadb_container
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: school_db
      MYSQL_USER: flask_user
      MYSQL_PASSWORD: flask_password

  flask_app:
    build:
      context: ./flask
      dockerfile: Dockerfile_flask
    container_name: flask_app_container
    ports:
      - "5000:5000"
    depends_on:
      - mariadb
    environment:
      FLASK_APP: app
      FLASK_ENV: development
      FLASK_DB_HOST: mariadb
      FLASK_DB_USER: flask_user
      FLASK_DB_PASSWORD: flask_password
      FLASK_DB_NAME: school_db

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    container_name: prometheus
    ports:
      - "9090:9090"
    depends_on:
      - flask_app

  grafana:
    build:
      context: ./grafana
      dockerfile: Dockerfile_grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      # Mapear a pasta de provisionamento corretamente
      - ./grafana/provisioning/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
      - ./grafana/provisioning/dashboard.yml:/etc/grafana/provisioning/dashboards/dashboard.yml
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards
      # Volume persistente para armazenar dados do Grafana
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus


volumes:
  db_data:
  grafana_data:
  
networks:
  app_network:
    driver: bridge
