global:
  scrape_interval: 15s  # Intervalo padrão de coleta de métricas para todos os jobs

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']  # Nome do serviço Flask no Docker Compose e porta

  - job_name: 'flask_app'
    static_configs:
      - targets: ['flask_app:5000']
