FROM grafana/grafana:latest

# Copiar os arquivos de provisionamento
COPY provisioning/datasource.yml /etc/grafana/provisioning/datasources/datasource.yml
COPY provisioning/dashboard.yml /etc/grafana/provisioning/dashboards/dashboard.yml

# Copiar os dashboards
COPY dashboards/ /var/lib/grafana/dashboards/

# Ajustar permissões para o usuário do Grafana
USER root
RUN chown -R 472:472 /etc/grafana /var/lib/grafana
USER 472
